# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32281cb7d90ebabd3877e0d6d727bac215c0cbf723ac8e78602745df5143013139fafaa875786d26d5f106e3547765d41f4d07988e02a6f06b279f985f4c2cc3

test:
  secret_key_base: c9007a08af440d00791089e9db25ad498242197419aca8179e9aa4312830b608e9f3e176c96feb94e508d364c71dcc2ccf996357141eda56224a83721467e7e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
